name: S3 Sync
on [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Sync to S3
        uses: raulanatol/aws-s3-docker-action@master
        env:
          AWS_ACCESS_KEY_ID:
          AWS_SECRET_ACCESS_KEY:
          AWS_REGION: 
          AWS_BUCKET_NAME: 
          SOURCE: 
          TARGET: 
          WITH_DELETE: 
          WITH_CLOUD_FRONT_INVALIDATION: 
          AWS_CLOUDFRONT_DISTRIBUTION_ID: 
          AWS_CLOUDFRONT_INVALIDATION_PATH:
